# Generated by Django 2.2.6 on 2019-12-06 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drinks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pump',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.PositiveSmallIntegerField()),
                ('address', models.PositiveSmallIntegerField()),
                ('contents', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drinks.Ingredient')),
            ],
        ),
    ]
