# Generated by Django 2.2.9 on 2020-01-10 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('barkeep', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pump',
            name='contents',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='drinks.Ingredient'),
        ),
    ]
