"""empty message

Revision ID: 6b4dcd28e911
Revises: 
Create Date: 2021-10-06 16:38:13.482639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b4dcd28e911'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('config',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('key', sa.String(length=255), nullable=False),
                    sa.Column('value', sa.String(length=255), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('drink',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=255), nullable=False),
                    sa.Column('image', sa.String(length=1024), nullable=True),
                    sa.Column('opendrinks', sa.Boolean(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('ingredient',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=255), nullable=False),
                    sa.Column('measure', sa.String(length=32), nullable=False),
                    sa.Column('carbonated', sa.Boolean(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('drink_alias',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('drink_id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=255), nullable=False),
                    sa.ForeignKeyConstraint(['drink_id'], ['drink.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('drink_ingredient',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('ingredient_id', sa.Integer(), nullable=False),
                    sa.Column('drink_id', sa.Integer(), nullable=False),
                    sa.Column('quantity', sa.Float(), nullable=False),
                    sa.Column('required', sa.Boolean(), nullable=False),
                    sa.ForeignKeyConstraint(['drink_id'], ['drink.id'], ),
                    sa.ForeignKeyConstraint(
                        ['ingredient_id'], ['ingredient.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('valve',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('pin', sa.Integer(), nullable=True),
                    sa.Column('ingredient_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['ingredient_id'], ['ingredient.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('valve')
    op.drop_table('drink_ingredient')
    op.drop_table('drink_alias')
    op.drop_table('ingredient')
    op.drop_table('drink')
    op.drop_table('config')
    # ### end Alembic commands ###
