# Generated by Django 2.2.6 on 2019-12-12 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='color',
            field=models.CharField(default='FFFFFF', max_length=6),
        ),
        migrations.AlterField(
            model_name='drink',
            name='name',
            field=models.CharField(default='Untitled', max_length=256),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(default='Untitled', max_length=128),
        ),
        migrations.AlterField(
            model_name='ingredienttype',
            name='name',
            field=models.CharField(default='Untitled', max_length=128),
        ),
    ]
