# Generated by Django 2.2.6 on 2019-12-19 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0002_auto_20191212_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.User'),
        ),
    ]
