# Generated by Django 2.2.6 on 2019-12-22 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0005_auto_20191220_0805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='color',
            field=models.CharField(default='#FFFFFF', max_length=7),
        ),
        migrations.AlterField(
            model_name='drink',
            name='image',
            field=models.ImageField(default='images/default.jpg', upload_to='images/'),
        ),
    ]
