# Generated by Django 2.2.6 on 2019-12-23 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0006_auto_20191222_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='name',
            field=models.CharField(max_length=256),
        ),
    ]
