# Generated by Django 3.0.2 on 2020-02-14 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0007_auto_20191222_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='ingredienttype',
            name='name',
            field=models.CharField(max_length=128),
        ),
    ]
