# Generated by Django 2.2.9 on 2020-01-24 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oz_interval', models.IntegerField(default=100)),
                ('name', models.CharField(default='Bartender', max_length=32)),
                ('color', models.CharField(default='#b87333', max_length=32)),
            ],
        ),
    ]
