# Generated by Django 3.0.2 on 2020-01-31 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bartender', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='oz_interval',
            field=models.IntegerField(default=1000),
        ),
    ]
